version: "3.8"

services:
  vpn_gateway:
    build:
      context: ./vpn_gateway
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./vpn_gateway/vpn_configs:/etc/openvpn
    restart: always

  ai_worker:
    build:
      context: .
      dockerfile: ./ai_worker/Dockerfile.ai
    depends_on:
      - vpn_gateway
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - .:/app
      - ./ai_worker/models:/app/models
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - backend

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile.parser
    depends_on:
      - vpn_gateway
    networks:
      - backend

  telegram_bot:
    build:
      context: .
      dockerfile: ./telegram_bot/Dockerfile.bot
    volumes:
      - ./telegram_bot:/app
    depends_on:
      - api
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - parser
    networks:
      - backend

networks:
  backend:
    driver: bridge
