version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fastuser
      POSTGRES_PASSWORD: fastpass
      POSTGRES_DB: fastdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: