services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.api
    container_name: tenderbotaiproject-api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - ai_worker
    networks:
      - tender-net

  telegram_bot:
    build:
      context: .
      dockerfile: telegram_bot/Dockerfile.bot
    container_name: tenderbotaiproject-telegram-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - api
    networks:
      - tender-net

  watchdog:
    build:
      context: .
      dockerfile: watchdog/Dockerfile.watchdog
    container_name: tenderbotaiproject-watchdog
    restart: always
    env_file:
      - .env
    networks:
      - tender-net

  ai_worker:
    build:
      context: .
      dockerfile: ai_worker/Dockerfile.ai
    container_name: tenderbotaiproject-ai-worker
    restart: always
    env_file:
      - .env
    networks:
      - tender-net

networks:
  tender-net:
    driver: bridge
