FROM python:3.11

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код бота
COPY . .

# Переменные окружения
ENV PYTHONUNBUFFERED=1

# Стартуем
CMD ["python", "bot.py"]
