FROM python:3.11

WORKDIR /app

COPY eis_api/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY eis_api/ /app/eis_api
COPY common/ /app/common

ENV PYTHONPATH=/app
CMD ["python", "-m", "eis_api.eis_client"]
