FROM alpine:3.20
RUN apk add --no-cache bash openvpn iproute2
WORKDIR /app
COPY start.sh /app/start.sh
COPY fix_ovpn.sh /app/fix_ovpn.sh
RUN chmod +x /app/start.sh /app/fix_ovpn.sh
CMD ["/app/start.sh"]
