FROM python:3.11

WORKDIR /app

# Путь относительный к context (а context — это ./ai_worker)
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код из ai_worker внутрь контейнера
COPY . .

# Указываем рабочую директорию
WORKDIR /app

# Запуск
CMD ["python", "run_ai_worker.py"]
