FROM python:3.11

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Установка Playwright браузеров
RUN python -m playwright install --with-deps

# Копируем остальной код
COPY . .

# Точка входа
CMD ["python", "main.py"]
