FROM ubuntu:22.04

# Установка Python и утилит (без openvpn)
RUN apt-get update && \
    apt-get install -y curl python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /app

COPY ./ai_worker /app/ai_worker
COPY ./tests /app/tests
COPY ./ai_worker/requirements.txt /app/requirements.txt

RUN pip3 install --no-cache-dir -r /app/requirements.txt

CMD ["python", "/app/ai_worker/ai.py"]
