FROM ubuntu:22.04

# Обновление и установка нужных пакетов
RUN apt-get update && \
    apt-get install -y openvpn curl python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python

# Установка зависимостей
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt

# Копируем VPN-конфиг и скрипт
COPY ai.py /app/ai.py

# Запускаем VPN и потом скрипт
CMD openvpn --config /etc/openvpn/vpngate_24.253.99.103_tcp_1721.ovpn --daemon && \
    sleep 10 && \
    python /app/ai.py
