FROM python:3.11

WORKDIR /app

COPY watchdog /app/watchdog
COPY watchdog/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["python", "watchdog/watchdog.py"]
