FROM python:3.11

WORKDIR /app

# Копируем всё содержимое watchdog внутрь контейнера
COPY . /app

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Запуск watchdog
CMD ["python", "watchdog/watchdog.py"]

