FROM python:3.11

WORKDIR /app

# requirements.txt лежит в этой же папке telegram_bot
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код бота
COPY . .

ENV PYTHONUNBUFFERED=1

ENV PYTHONPATH=/app

CMD ["python", "bot.py"]
