FROM python:3.11

WORKDIR /app

# копируем requirements.txt
COPY api/requirements.txt /app/requirements.txt

# устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

COPY api /app/api
COPY parsers /app/parsers
COPY common /app/common

ENV PYTHONPATH=/app

CMD ["uvicorn", "api.core:app", "--host", "0.0.0.0", "--port", "8000"]
