FROM python:3.11

WORKDIR /app

# Копируем requirements
COPY api/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код
COPY api /app/api
COPY ai_worker /app/ai_worker
COPY common /app/common
COPY main.py /app/main.py

ENV PYTHONPATH=/app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
